---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
spec:
  selector:
    matchLabels:
      app: javawebapp
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: ram204/java-web-app-docker
        imagePullPolicy: Always
        ports:
        - name: javawebapp
          containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: javawebapp
  labels:
    app: javawebapp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
  selector:
    app: javawebapp
